[mongodb]
mongodb.devopstech.shop

[redis]
redis.devopstech.shop

[mysql]
mysql.devopstech.shop

[rabbitmq]
rabbitmq.devopstech.shop

[catalogue]
catalogue.devopstech.shop

[user]
user.devopstech.shop

[cart]
cart.devopstech.shop

[shipping]
shipping.devopstech.shop

[payment]
payment.devopstech.shop

[frontend]
